#pragma once
#include <a.h>
#include <discord_rpc.h>
#include <fstream>
#include <cstddef>
#include <raylib.h>
#include <websocketpp/config/asio_no_tls.hpp>
#include <websocketpp/client.hpp>
#include <thread>
#include <common.h>
#include <settings.h>
#include <colors.h>
#include <title.h>
#include <loading.h>