#pragma once
#include <a.h>
#include <discord_rpc.h>
#include <ball.h>
#include <raylib.h>
#include <common.h>
#include <paddle.h>
#include <settings.h>
#include <colors.h>
#include <title.h>
#include <loading.h>